#server.port
server:
  port: 18083
#application.name
#spring:
#  devtools:
#    add-properties: true
#  application:
#    name: gateWay_service
## gateway 配置
#  cloud:
#    gateway:
## 开启网关配
#      routes:
##        路由编号【标识路由名称】
#        - id: path_route
##          路由url最后需要路由的地址
#          uri: http://127.0.0.1:18081
##          路由前缀匹配 【path / method 等】
#          predicates:
##            - Path=/kafka
##            拦截器
##            filters:
##            - StripPrefix=1


spring:
  application:
    name: gateWay_service
  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        - id: path_route # 路由的编号
          uri: lb://kafka-service # 路由到的目标地址
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/kafka/test
        - id: url-proxy-1
          uri: https://blog.csdn.net
          predicates:
            - Path=/csdn
      discovery:
        locator:
          enabled: true # 是否开启，默认为 false 关闭
          url-expression: "'lb://' + serviceId" # 路由的目标地址的表达式，默认为 "'lb://' + serviceId"
          lower-case-service-id: true # 服务名小写
    # 整合注册中心
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        ##注册到consul的服务名称
        service-name: gateWay_service
        enabled: true